version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      - /data/xxxx:/xxx
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://xxxx:xxxx@xxxx:5432/xxxx

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
  redis:
    image: "redis"
    ports:
      - "6379:6379"

  celery-flower:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: ["celery", "-A", "task.celery", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
